// <auto-generated />
using System;
using Isbasatis.LicenseManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Isbasatis.LicenseManager.API.Migrations
{
    [DbContext(typeof(LicenseContext))]
    [Migration("20211122125740_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LicenseCount")
                        .HasColumnType("int");

                    b.Property<int>("LicenseType")
                        .HasColumnType("int");

                    b.Property<int>("OnlineLisans")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModuleTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("InfoType")
                        .HasColumnType("int");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("systemInfos");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.Module", b =>
                {
                    b.HasOne("Isbasatis.LicenseManager.LicenseInformations.Tables.License", null)
                        .WithMany("Modules")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.SystemInfo", b =>
                {
                    b.HasOne("Isbasatis.LicenseManager.LicenseInformations.Tables.License", null)
                        .WithMany("SystemInfos")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.LicenseInformations.Tables.License", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("SystemInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
