// <auto-generated />
using System;
using Isbasatis.LicenseManager.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Isbasatis.LicenseManager.API.Migrations
{
    [DbContext(typeof(LicenseContext))]
    partial class LicenseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.License", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LicenseCount")
                        .HasColumnType("int");

                    b.Property<int>("LicenseType")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ModuleTypeEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("modules");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.SystemInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Info")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InfoType")
                        .HasColumnType("int");

                    b.Property<Guid?>("LicenseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LicenseId");

                    b.ToTable("systemInfos");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.Module", b =>
                {
                    b.HasOne("Isbasatis.LicenseManager.API.Data.Tables.License", null)
                        .WithMany("Modules")
                        .HasForeignKey("LicenseId");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.SystemInfo", b =>
                {
                    b.HasOne("Isbasatis.LicenseManager.API.Data.Tables.License", null)
                        .WithMany("SystemInfos")
                        .HasForeignKey("LicenseId");
                });

            modelBuilder.Entity("Isbasatis.LicenseManager.API.Data.Tables.License", b =>
                {
                    b.Navigation("Modules");

                    b.Navigation("SystemInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
